### ISSUE TITLE
Documentation for Emitted Events

### ISSUE THREAD

**Issue by chenxeed** [propellant/doctor#10]
Hi! I think for the documentation of emitted events is useful too so that we can determine what is the child emitted values.

Since for the way to use component is, to send data through `props` and to listen to the `emit` events. I believe both of these functionality should be documented as well.

**Comment by pearofducks** [comment]
I agree, and am open to suggestions on how to programmatically build these up.

IMO these probably need to be handled by the extra metadata fields already provided, because just parsing them in a table isn't enough, most would need annotation to have meaning.
