### ISSUE TITLE
Markdown in notes

### ISSUE THREAD

**Issue by Solinx** [propellant/doctor#14]
Would it be possible to support markdown processing for the notes in properties? Thanks!

**Comment by pearofducks** [comment]
Unfortunately this would be a major breaking change to the current behavior — and I don't see a strong benefit for adding it.

You should easily be able to patch it in by modifying [this assignment](https://github.com/propellant/doctor/blob/master/propDoc.vue#L84) with a call to `marked`, and then of course change the template to support what is rendered [here](https://github.com/propellant/doctor/blob/master/propDoc.vue#L22)

**Comment by Solinx** [comment]
Fair enough. We're indeed going to be working around it by extending your component. Thanks for the pointers!
