### ISSUE TITLE
Output markdown to files

### ISSUE THREAD

**Issue by robcresswell** [propellant/doctor#3]
Hi,

I had a scan through the project and it seems at the moment that markdown is pulled from the components then render in a browser via Vue. Have you considered just outputting the compiled markdown to a folder? It would be really helpful for documentation generation.

**Comment by pearofducks** [comment]
I'm completely open to accepting PRs that add this functionality. We could pretty easily separate out the parsing logic and share that between the Vue component and a Markdown-creating lib.

I don't have time right now to dedicate to adding that functionality, but am happy to discuss and support!

**Comment by robcresswell** [comment]
Awesome. I'll take a look when I get a few free hours, see if I can come up with something straightforward. Thanks for taking the time to respond, I really appreciate it.

**Comment by robcresswell** [comment]
Hey, just wanted to dropa message saying I'm still interested in looking at this; just haven't found a few free hours to hack on it.

**Comment by aflashyrhetoric** [comment]
Hello hello @robcresswell - just wanted to ping to see if you had any time to pick this up? Seems like a really great feature and I am considering trying my hand at it as well.

**Comment by robcresswell** [comment]
@aflashyrhetoric Go ahead; I never got round to it. I agree it'd be cool :)
